create table if not exists countries (
  id bigint generated by default as identity primary key,
  name text not null,
  visa text not null,
  insurance text not null,
  risk text not null,
  medical int not null default 3,
  safety int not null default 3,
  disaster int not null default 2,
  description text,
  recommendation text,
  created_at timestamptz default now()
);

create table if not exists applications (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  country text not null,
  policy text not null,
  travel_date text,
  status text not null default 'Simulated policy issued',
  created_at timestamptz default now()
);

create table if not exists audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_email text,
  action text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);
